name: Publish to Private API Network

on:
  push:
    branches: ['main']

jobs:
  parse-api-version:
    runs-on: ubuntu-latest
    outputs:
      api-version: ${{ steps.parse-api-version.outputs.value }}
    steps:
      - uses: actions/checkout@v3
      - name: Install jq
        id: parse-api-version
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq .info.version schema/swagger_output.json
      - name: Print API Version
        run: echo ${{ steps.parse-api-version.outputs.value }}
  publish-api:
    needs: [parse-api-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Publish API
        run: |
          postman api publish ab85f29b-f241-4e8b-83bf-5432841f8154 \
          --name "${{needs.parse-api-version.outputs.api-version}}" \
          --release-notes "#Version: ${{needs.parse-api-version.outputs.api-version}}"\
